CREATE TABLE IF NOT EXISTS users (
    id INT NOT NULL PRIMARY KEY GENERATED ALWAYS AS IDENTITY
    , email CITEXT UNIQUE NOT NULL
    , password text NOT NULL
    , nickname CITEXT UNIQUE NOT NULL
    );